window.enemies = {
  s001: {
    name: "Morcego",
    description: "Pequeno Morcego",
    type: "normal",
    team: "enemy",
    src: "/image/enemies/Bat.png",
    xp: 100,
    hp: 99,
    maxHp: 99,
    defense: 14,
    magicDefense: 12,
    attack: 30,
    magicAttack: 30,
    // weakness: "fire",
    actions: ["bite", "absorbBat"],
    statusEffects: null,
  },
  s002: {
    name: "Rato",
    description: "Pequeno Rato",
    team: "enemy",
    src: "/image/enemies/Rat.png",
    xp: 125,
    hp: 92,
    maxHp: 92,
    defense: 19,
    magicDefense: 8,
    attack: 35,
    magicAttack: 0,
    actions: ["bite", "poisonBite"],
    statusEffects: null,
  },
  s003: {
    name: "Earwig",
    team: "enemy",
    src: "/image/enemies/Earwig.png",
    xp: 105,
    hp: 107,
    maxHp: 107,
    defense: 18,
    magicDefense: 17,
    attack: 31,
    magicAttack: 0,
    actions: ["bite"],
    statusEffects: null,
  },
  s004: {
    name: "Slime",
    team: "enemy",
    src: "/image/enemies/Slime.png",
    xp: 140,
    hp: 137,
    maxHp: 137,
    maxMp: 23,
    defense: 31,
    magicDefense: 4,
    attack: 32,
    magicAttack: 0,
    actions: ["blow", "mobSleepStatus"],
    statusEffects: null,
  },
  s005: {
    name: "Mushroom",
    team: "enemy",
    src: "/image/enemies/Mushroom.png",
    xp: 150,
    hp: 101,
    maxHp: 101,
    defense: 22,
    magicDefense: 24,
    attack: 45,
    magicAttack: 0,
    actions: ["blow", "mobSleepStatus"],
    statusEffects: null,
  },
  s006: {
    name: "Crab",
    team: "enemy",
    src: "/image/enemies/Crab.png",
    xp: 130,
    hp: 151,
    maxHp: 151,
    defense: 18,
    magicDefense: 16,
    attack: 50,
    magicAttack: 0,
    actions: ["scissor"],
    statusEffects: null,
  },
  s007: {
    name: "Salamandra",
    team: "enemy",
    src: "/image/enemies/Salamandra.png",
    xp: 200,
    hp: 99,
    maxHp: 99,
    defense: 23,
    magicDefense: 50,
    attack: 30,
    magicAttack: 40,
    actions: ["bite", "mobFire"],
    statusEffects: null,
  },
  s008: {
    name: "Worm",
    team: "enemy",
    src: "/image/enemies/Worm.png",
    xp: 180,
    hp: 161,
    maxHp: 161,
    defense: 33,
    magicDefense: 25,
    attack: 77,
    magicAttack: 0,
    actions: ["bite"],
    statusEffects: null,
  },
  s009: {
    name: "Anemone",
    team: "enemy",
    src: "/image/enemies/Anemone.png",
    xp: 310,
    hp: 215,
    maxHp: 215,
    defense: 50,
    magicDefense: 40,
    attack: 79,
    magicAttack: 0,
    actions: ["scissor"],
    statusEffects: null,
  },
  s010: {
    name: "Green Orb",
    team: "enemy",
    src: "/image/enemies/GreenOrb.png",
    xp: 400,
    hp: 187,
    maxHp: 187,
    defense: 30,
    magicDefense: 60,
    attack: 0,
    magicAttack: 105,
    actions: ["mobWater"],
    statusEffects: null,
  },
  c001: {
    name: "Orc",
    team: "enemy",
    src: "/image/enemies/Orc.png",
    xp: 550,
    hp: 400,
    maxHp: 400,
    defense: 84,
    magicDefense: 75,
    attack: 92,
    magicAttack: 0,
    actions: ["axe", "powerAxe"],
    statusEffects: null,
  },
  c002: {
    name: "Skeleton",
    team: "enemy",
    src: "/image/enemies/Skeleton.png",
    xp: 600,
    hp: 363,
    maxHp: 363,
    defense: 67,
    magicDefense: 68,
    attack: 108,
    magicAttack: 0,
    actions: ["skeletonSword"],
    statusEffects: null,
  },
  c003: {
    name: "Mimic",
    team: "enemy",
    src: "/image/enemies/Mimic.png",
    xp: 650,
    hp: 337,
    maxHp: 337,
    defense: 55,
    magicDefense: 66,
    attack: 0,
    magicAttack: 120,
    actions: ["mobFire", "mobWater", "mobIce"],
    statusEffects: null,
  },
  c004: {
    name: "Spider",
    team: "enemy",
    src: "/image/enemies/Spider.png",
    xp: 700,
    hp: 299,
    maxHp: 299,
    defense: 65,
    magicDefense: 72,
    attack: 97,
    magicAttack: 0,
    actions: ["bite", "poisonBite2"],
    statusEffects: null,
  },
  c005: {
    name: "Mini Demon",
    team: "enemy",
    src: "/image/enemies/miniDemon.png",
    xp: 680,
    hp: 255,
    maxHp: 255,
    defense: 71,
    magicDefense: 82,
    attack: 87,
    magicAttack: 96,
    actions: ["demonSpear", "mobThunder"],
    statusEffects: null,
  },

  // Mini-Bosses
  Mini_Boss001: {
    name: "Pegasus Knight",
    team: "enemy",
    src: "/image/bosses/PegasusKnight.png",
    xp: 850,
    hp: 570,
    maxHp: 570,
    defense: 80,
    magicDefense: 50,
    attack: 80,
    magicAttack: 0,
    actions: ["lance", "chargeLance", "blackShield"],
    statusEffects: null,
  },
  Mini_Boss002: {
    name: "Guardian",
    team: "enemy",
    src: "/image/bosses/Guardian.png",
    xp: 700,
    hp: 700,
    maxHp: 700,
    defense: 70,
    magicDefense: 50,
    attack: 78,
    magicAttack: 0,
    actions: ["halberd", "bloodHalberd"],
    statusEffects: null,
  },
  Mini_Boss003: {
    name: "Reaper",
    team: "enemy",
    src: "/image/bosses/Reaper.png",
    xp: 1200,
    hp: 650,
    maxHp: 650,
    defense: 81,
    magicDefense: 81,
    attack: 105,
    magicAttack: 0,
    actions: ["scythe", "soulDestruction"],
    statusEffects: null,
  },

  // Bosses
  Boss001: {
    name: "Gades",
    team: "enemy",
    src: "/image/bosses/Gades.png",
    xp: 4000,
    hp: 1050,
    maxHp: 1050,
    defense: 171,
    magicDefense: 131,
    attack: 175,
    magicAttack: 0,
    actions: ["gadesSword", "destroy", "champion"],
    statusEffects: null,
  },
  Boss002: {
    name: "Amon",
    team: "enemy",
    src: "/image/bosses/Amon.png",
    xp: 6000,
    hp: 998,
    maxHp: 998,
    defense: 125,
    magicDefense: 230,
    attack: 140,
    magicAttack: 210,
    actions: ["amonStaff", "amonBlast", "magicBlessing"],
    statusEffects: null,
  },
  Boss003: {
    name: "Erim",
    team: "enemy",
    src: "/image/bosses/Erim.png",
    xp: 8000,
    hp: 1115,
    maxHp: 1115,
    defense: 144,
    magicDefense: 210,
    attack: 155,
    magicAttack: 190,
    actions: [
      "waterSpear",
      "erimFlood",
      "erimWater",
      "erimThunder",
      "erimFlash",
    ],
    statusEffects: null,
  },
  Boss004: {
    name: "Daos",
    team: "enemy",
    src: "/image/bosses/Daos.png",
    xp: 10000,
    hp: 1300,
    maxHp: 1300,
    defense: 201,
    magicDefense: 260,
    attack: 199,
    magicAttack: 230,
    actions: ["daosHand", "daosVulcan", "attackFullBoost"],
    statusEffects: null,
  },
  Boss005: {
    name: "Felicia",
    team: "enemy",
    src: "/image/bosses/DemonPrincess.png",
    xp: 20000,
    hp: 2500,
    maxHp: 2500,
    defense: 250,
    magicDefense: 250,
    attack: 0,
    magicAttack: 350,
    actions: ["darknessHand", "cyrstalRain", "cyrstalFelicia"],
    statusEffects: null,
  },

  // Heros
  hero1: {
    name: "Ishtar",
    description: "A Heroina. Mestre das Espadas e Aprendiz de Magia",
    team: "hero",
    src: "image/heroes/Hero1.png",
    hp: 86, //86
    maxHp: 86,
    mp: 23,
    maxMp: 23,
    xp: 0,
    maxXp: 71, //71
    defense: 19, 
    magicDefense: 11, 
    attack: 27,
    magicAttack: 16,
    level: 1,
    actions: [
      "ishtarSword",
      "ishtarDualBlade",
      "ishtarSonicBlade",
      "ishtarFireSword",
      "ishtarSleep",
      "blessHero",
      "blessHero2",
      "ishtarDanceofSword",
    ],
    isPlayerControlled: true,
    statusEffects: null,
  },
  hero2: {
    name: "Freya",
    description:
      "Melhor amiga de Ishtar. Uma poderosa maga perita em magias de fogo e água além de conhecer um pouco de magia suporte",
    team: "hero",
    src: "image/heroes/Hero2.png",
    hp: 76,
    maxHp: 76,
    mp: 26,
    maxMp: 26,
    xp: 0,
    maxXp: 75,
    defense: 14,
    magicDefense: 15,
    attack: 17,
    magicAttack: 28,
    level: 1,
    actions: [
      "freyaStaff",
      "freyaMeditate",
      "freyaRainofBlades",
      "freyaWater",
      "freyaFire",
      "freyaFlood",
      "freyaVulcan",
      "freyaHeal",
      "freyaMagicZone",
      "freyaHeal2",
    ],
    isPlayerControlled: true,
    statusEffects: null,
  },
  hero3: {
    name: "Celestia",
    description:
      "Uma Hibrida Humana e Demonio, conhecedora da Magia normal e a magia proibida.",
    team: "hero",
    src: "image/heroes/Hero3.png",
    hp: 68,
    maxHp: 68,
    mp: 30,
    maxMp: 30,
    xp: 0,
    maxXp: 72,
    defense: 12,
    magicDefense: 20,
    attack: 20,
    magicAttack: 24,
    level: 1,
    actions: [
      "celestiaDarkStaff",
      "celestiaIce",
      "celestiaAbsorb",
      "celestiaShield",
      "celestiaSoulBreak",
      "celestiaBlizzard",
      "celestiaVampirism",
      "celestiaMagicDrain",
    ],
    isPlayerControlled: true,
    statusEffects: null,
  },
  hero4: {
    name: "Aerin",
    description: "Princesa Elfa, perita em magia e na arte da espada ",
    team: "hero",
    src: "image/heroes/Hero4.png",
    hp: 91,
    maxHp: 91,
    mp: 20,
    maxMp: 20,
    xp: 0,
    maxXp: 77,
    defense: 16,
    magicDefense: 19,
    attack: 24,
    magicAttack: 16,
    level: 1,
    actions: [
      "aerinRapier",
      "aerinMagicDagger",
      "aerinInfusionBlade",
      "aerinBattleDance",
      "aerinBolt",
      "aerinElfSecretBlessing",
      "aerinElfSecretBlessing2",
    ],
    isPlayerControlled: true,
    statusEffects: null,
  },
};
