window.enemies = {
    "s001": {
      name: "Morcego",
      description: "Pequeno Morcego",
      type: "normal",
      team: "enemy",
      src: "/image/enemies/Bat.png",
      level:2,
      hp: 5,
      maxHp: 120,
      mp: 20,
      maxMp: 50,
      xp: 50,
      defense: 5,
      magicDefense: 40,
      agility: 15,
      attack: 30,
      magicAttack: 10,
      magic: "Fireball",
      weakness: "fire",
      actions: ["bite","absorbBat",],
      status: null,
    },
    "s002": {
      name: "Rato",
      description: "Pequeno Rato",
      team: "enemy",
      src: "/image/enemies/Rat.png",
      level:1,
      hp: 30,
      maxHp: 70,
      xp: 20,
      defense: 15,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 5,
      actions: ["bite"],
      status: null,
    },
    "s003": {
      name: "Earwig",
      team: "enemy",
      src: "/image/enemies/Earwig.png",
      hp: 30,
      maxHp: 70,
      xp: 20,
      defense: 15,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 0,
      actions: ["bite","sleepStatus",],
      status: null,
    },
    "s004": {
      name: "Slime",
      team: "enemy",
      src: "/image/enemies/Slime.png",
      hp: 70,
      maxHp: 70,
      xp: 20,
      defense: 15,
      magicDefense: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["melee_attack",],
      status: null,
    },
    "s005": {
      name: "Cogumelo",
      team: "enemy",
      src: "/image/enemies/Mushroom.png",
      hp: 30,
      maxHp: 70,
      xp: 20,
      defense: 15,
      magicDefense: 40,
      attack: 20,
      magicAttack: 40,
      actions: ["melee_attack","sleepStatus",],
      status: null,
    },
    "s006": {
      name: "Crab",
      team: "enemy",
      src: "/image/enemies/Crab.png",
      hp: 70,
      level:1,
      maxHp: 70,
      xp: 20,
      defense: 0,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["melee_attack"],
      status: null,
    },
    "s007": {
      name: "Salamandra",
      team: "enemy",
      src: "/image/enemies/Salamandra.png",
      hp: 70,
      level:1,
      maxHp: 70,
      xp: 20,
      defense: 0,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["melee_attack"],
      status: null,
    },
    "s008": {
      name: "Worm",
      team: "enemy",
      src: "/image/enemies/Worm.png",
      hp: 70,
      level:1,
      maxHp: 70,
      xp: 20,
      defense: 0,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["melee_attack"],
      status: null,
    },
    "s009": {
      name: "Anemone",
      team: "enemy",
      src: "/image/enemies/Anemone.png",
      hp: 70,
      level:1,
      maxHp: 70,
      xp: 20,
      defense: 0,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["melee_attack"],
      status: null,
    },
    "s010": {
      name: "Green Orb",
      team: "enemy",
      src: "/image/enemies/GreenOrb.png",
      hp: 70,
      level:1,
      maxHp: 70,
      xp: 20,
      defense: 0,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["melee_attack"],
      status: null,
    },
    "c001": {
      name: "Orc",
      team: "enemy",
      src: "/image/enemies/Orc.png",
      hp: 70,
      level:1,
      maxHp: 70,
      xp: 20,
      defense: 0,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["melee_attack"],
      status: null,
    },
    "c002": {
      name: "Skeleton",
      team: "enemy",
      src: "/image/enemies/Skeleton.png",
      hp: 70,
      level:1,
      maxHp: 70,
      xp: 20,
      defense: 0,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["melee_attack"],
      status: null,
    },

    // Mini-Bosses
    "Mini_Boss001": {
      name: "Pegasus Knight",
      team: "enemy",
      src:"/image/bosses/PegasusKnight.png",
      hp: 1,
      maxHp: 3500,
      defense: 150,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["melee_attack"],
      status: null,
    },
    "Mini_Boss002": {
      name: "Guardian",
      team: "enemy",
      src:"/image/bosses/Guardian.png",
      hp: 1,
      maxHp: 3500,
      defense: 35,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["melee_attack"],
      status: null,
    },
    "Mini_Boss003": {
      name: "Reaper",
      team: "enemy",
      src:"/image/bosses/Reaper.png",
      hp: 1,
      maxHp: 3500,
      defense: 150,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["melee_attack"],
      status: null,
    },

    // Bosses
    "Boss001": {
      name: "Gades",
      team: "enemy",
      src:"/image/bosses/Gades.png",
      hp: 1,
      maxHp: 3500,
      defense: 150,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["melee_attack"],
      status: null,
    },
    "Boss002": {
      name: "Amon",
      team: "enemy",
      src:"/image/bosses/Amon.png",
      hp: 1,
      maxHp: 3500,
      defense: 150,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["melee_attack"],
      status: null,
    },
    "Boss003": {
      name: "Erim",
      team: "enemy",
      src:"/image/bosses/Erim.png",
      hp: 1,
      maxHp: 3500,
      defense: 150,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["waterSpear","erimFlood","erimWater","erimThunder","erimFlash"],
      status: null,
    },
    "Boss004": {
      name: "Daos",
      team: "enemy",
      src:"/image/bosses/Daos.png",
      hp: 1,
      maxHp: 3500,
      defense: 150,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["melee_attack"],
      status: null,
    },
    "Boss005": {
      name: "Felicia",
      team: "enemy",
      src:"/image/bosses/DemonPrincess.png",
      hp: 1,
      maxHp: 3500,
      defense: 150,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["melee_attack"],
      status: null,
    },

    // Heros
    "hero1": {
      name: "Ishtar",
      description: "Mestre das Espadas e Aprendiz de Magia",
      team: "hero",
      src: "image/heroes/Hero1.png",
      hp: 1000,
      maxHp: 1150,
      mp: 20,
      maxMp: 50,
      xp: 70,
      maxXp: 100,
      defense: 5,
      magicDefense: 10,
      attack: 30,
      magicAttack: 10,
      level: 1,
      actions: ["melee_attack","sleepStatus","armorStatus","fire","erimFlood","bolt","berserker"],
      isPlayerControlled: true,
      status: null,
    },
    "hero2": {
      name: "Freya",
      description: "Mão Direita da Rainha",
      team: "hero",
      src: "image/heroes/Hero2.png",
      hp: 100,
      maxHp: 150,
      mp: 20,
      maxMp: 50,
      xp: 90,
      maxXp: 100,
      defense: 5,
      magicDefense: 10,
      attack: 30,
      magicAttack: 10,
      level: 1,
      actions: ["melee_attack","sleepStatus","armorStatus","absorb","ice"],
      isPlayerControlled: true,
      status: null,
      // Adicione outros atributos conforme necessário
    },
    "hero3": {
      name: "Celestia",
      description: "Uma poderosa Maga das vilas do norte",
      team: "hero",
      src: "image/heroes/Hero3.png",
      hp: 1000,
      maxHp: 1150,
      mp: 20,
      maxMp: 50,
      xp: 70,
      maxXp: 100,
      defense: 5,
      magicDefense: 10,
      attack: 30,
      magicAttack: 10,
      level: 1,
      actions: ["melee_attack","sleepStatus","armorStatus","fire","erimThunder","bolt","berserker"],
      isPlayerControlled: true,
      status: null,
    },
    "hero4": {
      name: "Aerin",
      description: "Princesa Elfa, perita em magia e na espada ",
      team: "hero",
      src: "image/heroes/Hero4.png",
      hp: 200,
      maxHp: 1150,
      mp: 20,
      maxMp: 50,
      xp: 70,
      maxXp: 100,
      defense: 5,
      magicDefense: 10,
      attack: 30,
      magicAttack: 10,
      level: 1,
      actions: ["melee_attack","sleepStatus","armorStatus","fire","erimThunder","bolt","berserker"],
      isPlayerControlled: true,
      status: null,
    },

    
  }
  