window.enemies = {
    "s001": {
      name: "Morcego",
      description: "Pequeno Morcego",
      type: "normal",
      team: "enemy",
      src: "/image/enemies/Bat.png",
      level:2,
      hp: 70,
      maxHp: 70,
      mp: 20,
      maxMp: 50,
      xp: 50,
      defense: 0,
      magicDefense: 0,
      agility: 15,
      attack: 30,
      magicAttack: 10,
      magic: "Fireball",
      weakness: "fire",
      actions: ["bite","absorbBat"],
      statusEffects: null,
    },
    "s002": {
      name: "Rato",
      description: "Pequeno Rato",
      team: "enemy",
      src: "/image/enemies/Rat.png",
      level:1,
      hp: 30,
      maxHp: 70,
      xp: 20,
      defense: 15,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 5,
      actions: ["bite","poisonBite"],
      statusEffects: null,
    },
    "s003": {
      name: "Earwig",
      team: "enemy",
      src: "/image/enemies/Earwig.png",
      hp: 30,
      maxHp: 70,
      xp: 20,
      defense: 15,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 0,
      actions: ["bite","mobSleepStatus"],
      statusEffects: null,
    },
    "s004": {
      name: "Slime",
      team: "enemy",
      src: "/image/enemies/Slime.png",
      hp: 70,
      maxHp: 70,
      xp: 20,
      defense: 15,
      magicDefense: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["blow","mobSleepStatus"],
      statusEffects: null,
    },
    "s005": {
      name: "Cogumelo",
      team: "enemy",
      src: "/image/enemies/Mushroom.png",
      hp: 30,
      maxHp: 70,
      xp: 20,
      defense: 15,
      magicDefense: 40,
      attack: 20,
      magicAttack: 40,
      actions: ["blow","mobSleepStatus"],
      statusEffects: null,
    },
    "s006": {
      name: "Crab",
      team: "enemy",
      src: "/image/enemies/Crab.png",
      hp: 70,
      level:1,
      maxHp: 70,
      xp: 20,
      defense: 0,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["scissor"],
      statusEffects: null,
    },
    "s007": {
      name: "Salamandra",
      team: "enemy",
      src: "/image/enemies/Salamandra.png",
      hp: 70,
      level:1,
      maxHp: 70,
      xp: 20,
      defense: 0,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["bite","mobFire"],
      statusEffects: null,
    },
    "s008": {
      name: "Worm",
      team: "enemy",
      src: "/image/enemies/Worm.png",
      hp: 70,
      level:1,
      maxHp: 70,
      xp: 20,
      defense: 0,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["bite"],
      statusEffects: null,
    },
    "s009": {
      name: "Anemone",
      team: "enemy",
      src: "/image/enemies/Anemone.png",
      hp: 70,
      level:1,
      maxHp: 70,
      xp: 20,
      defense: 0,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["scissor"],
      statusEffects: null,
    },
    "s010": {
      name: "Green Orb",
      team: "enemy",
      src: "/image/enemies/GreenOrb.png",
      hp: 70,
      level:1,
      maxHp: 70,
      xp: 20,
      defense: 0,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["mobWater"],
      statusEffects: null,
    },
    "c001": {
      name: "Orc",
      team: "enemy",
      src: "/image/enemies/Orc.png",
      hp: 70,
      level:1,
      maxHp: 70,
      xp: 20,
      defense: 0,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["melee_attack"],
      statusEffects: null,
    },
    "c002": {
      name: "Skeleton",
      team: "enemy",
      src: "/image/enemies/Skeleton.png",
      hp: 70,
      level:1,
      maxHp: 70,
      xp: 20,
      defense: 0,
      magicDefense: 10,
      agility: 10,
      attack: 20,
      magicAttack: 40,
      actions: ["melee_attack"],
      statusEffects: null,
    },

    // Mini-Bosses
    "Mini_Boss001": {
      name: "Pegasus Knight",
      team: "enemy",
      src:"/image/bosses/PegasusKnight.png",
      hp: 1,
      maxHp: 3500,
      defense: 150,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["lance","chargeLance","blackShield"],
      statusEffects: null,
    },
    "Mini_Boss002": {
      name: "Guardian",
      team: "enemy",
      src:"/image/bosses/Guardian.png",
      hp: 1,
      maxHp: 3500,
      defense: 35,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["halberd","bloodHalberd"],
      statusEffects: null,
    },
    "Mini_Boss003": {
      name: "Reaper",
      team: "enemy",
      src:"/image/bosses/Reaper.png",
      hp: 1,
      maxHp: 3500,
      defense: 150,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["scythe","soulDestruction"],
      statusEffects: null,
    },

    // Bosses
    "Boss001": {
      name: "Gades",
      team: "enemy",
      src:"/image/bosses/Gades.png",
      hp: 1,
      maxHp: 3500,
      defense: 150,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["gadesSword","destroy","champion"],
      statusEffects: null,
    },
    "Boss002": {
      name: "Amon",
      team: "enemy",
      src:"/image/bosses/Amon.png",
      hp: 1,
      maxHp: 3500,
      defense: 150,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["amonStaff","amonBlast","magicBlessing"],
      statusEffects: null,
    },
    "Boss003": {
      name: "Erim",
      team: "enemy",
      src:"/image/bosses/Erim.png",
      hp: 1,
      maxHp: 3500,
      defense: 150,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["waterSpear","erimFlood","erimWater","erimThunder","erimFlash"],
      statusEffects: null,
    },
    "Boss004": {
      name: "Daos",
      team: "enemy",
      src:"/image/bosses/Daos.png",
      hp: 1500,
      maxHp: 3500,
      defense: 150,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["daosHand","daosVulcan","attackFullBoost"],
      statusEffects: null,
    },
    "Boss005": {
      name: "Felicia",
      team: "enemy",
      src:"/image/bosses/DemonPrincess.png",
      hp: 1,
      maxHp: 3500,
      defense: 150,
      magicDefense: 200,
      attack: 350,
      magicAttack: 200,
      actions: ["darknessHand","cyrstalRain","cyrstalFelicia"],
      statusEffects: null,
    },

    // Heros
    "hero1": {
      name: "Ishtar",
      description: "A Heroina. Mestre das Espadas e Aprendiz de Magia",
      team: "hero",
      src: "image/heroes/Hero1.png",
      hp: 86,
      maxHp: 86,
      mp: 23,
      maxMp: 23,
      xp: 0,
      maxXp: 88,
      defense: 26,
      magicDefense: 9,
      attack: 32,
      magicAttack: 19,
      level: 1,
      actions: ["ishtarSword","blessHero", "blessHero2","ishtarDualBlade","ishtarFireSword","ishtarDanceofSword","ishtarSleep"],
      isPlayerControlled: true,
      statusEffects: null,
    },
    "hero2": {
      name: "Freya",
      description: "Melhor amiga de Ishtar. Uma poderosa maga perita em magias de fogo e água além de conhecer um pouco de magia suporte",
      team: "hero",
      src: "image/heroes/Hero2.png",
      hp: 76,
      maxHp: 76,
      mp: 26,
      maxMp: 26,
      xp: 0,
      maxXp: 92,
      defense: 16,
      magicDefense: 15,
      attack: 17,
      magicAttack: 28,
      level: 1,
      actions: ["freyaStaff","freyaWater","freyaFire","freyaVulcan","freyaFlood","freyaHeal","freyaHeal2"],
      isPlayerControlled: true,
      statusEffects: null,
    },
    "hero3": {
      name: "Celestia",
      description: "Uma Hibrida Humana e Demonio, conhecedora da Magia normal e a magia proibida.",
      team: "hero",
      src: "image/heroes/Hero3.png",
      hp: 68,
      maxHp: 68,
      mp: 31,
      maxMp: 31,
      xp: 0,
      maxXp: 90,
      defense: 14,
      magicDefense: 22,
      attack: 15,
      magicAttack: 24,
      level: 1,
      actions: ["celestiaDarkStaff","celestiaSoulBreak","celestiaAbsorb","celestiaIce","celestiaBlizzard","celestiaVampirism","celestiaShield"],
      isPlayerControlled: true,
      statusEffects: null,
    },
    "hero4": {
      name: "Aerin",
      description: "Princesa Elfa, perita em magia e na arte da espada ",
      team: "hero",
      src: "image/heroes/Hero4.png",
      hp: 91,
      maxHp: 91,
      mp: 17,
      maxMp: 17,
      xp: 0,
      maxXp: 94,
      defense: 21,
      magicDefense: 18,
      attack: 26,
      magicAttack: 16,
      level: 1,
      actions: ["aerinRapier","aerinMagicDagger","aerinBattleDance","aerinBolt", "aerinElfSecretBlessing", "aerinElfSecretBlessing2"],
      isPlayerControlled: true,
      statusEffects: null,
    },

    
  }
  